\c deeho1lp4038pr;

INSERT INTO animal_catalog 
(animal_name, class, location, description, price, stock, img) 
VALUES
('Sugar Glider','Mammal', 'Southeastern Australia', 'The sugar glider is a small, omnivorous, arboreal, and nocturnal gliding possum belonging to the marsupial infraclass.', '750', 'true', 'https://media.istockphoto.com/photos/sugar-glider-picture-id154225190?k=6&m=154225190&s=612x612&w=0&h=jKM1geP98kB_Ugr7CLqlp4eVylmi18-84WqlME3gQD8='),
('Fennec Fox', 'Mammal', 'Africa & Western Asia', 'The fennec fox is a small crepuscular fox native to the Sahara Desert, the Sinai Peninsula in Egypt, and the Arava and Negev deserts in Israel. Its most distinctive feature is its unusually large ears.', '4500', 'true', 'https://media.istockphoto.com/photos/fennec-fox-lying-down-on-a-white-background-glaring-picture-id153888922?k=6&m=153888922&s=612x612&w=0&h=gmgAIO7oWnt6AY_K5Mmqexnhe_2hZ81hjbt4uETNwPs='),
('Red Hand Tamarin', 'Mammal', 'Guyana & South America', 'The red-handed tamarin, also known as the golden-handed tamarin or Midas tamarin, is a New World monkey belonging to the family Callitrichidae.', '4500', 'false', 'https://media.istockphoto.com/photos/gold-handed-tamarin-monkey-is-resting-on-the-tree-branch-detail-look-picture-id1210601946?k=6&m=1210601946&s=612x612&w=0&h=vvudy5OQd4Zh10FFd_fGQCFHOrmmsmgbTemzySTP23w='),
('Albino Suriname Red Tailed Boa ', 'Reptile', 'Suriname (South America)', 'A sought-after reptile among snake lovers, the Suriname red tail boa is both rare and beautiful. This snake is technically not a separate species (just like the Colombian red tail). It’s part of the boa constrictor family','15000', 'true', 'https://nitrocdn.com/mmYpspjiwLqACCAMtoInlelNBxMLnEyf/assets/static/optimized/rev-7c84dce/wp-content/uploads/2020/08/Boa-constrictor-imperator-red-tailed-boa.jpg'),
('Chinchilla', 'Mammal', 'Andes Mountain', 'Chinchillas are either of two species (Chinchilla chinchilla and Chinchilla lanigera) of crepuscular rodents of the parvorder Caviomorpha.', '650', 'false', 'https://media.istockphoto.com/photos/little-gray-chinchilla-sits-in-a-wooden-bowl-picture-id491059172?k=6&m=491059172&s=612x612&w=0&h=KVk3Z8R6eq9wgX4oY1qOKUj8t8mnErLaHZxS2zNdt28='),
('Bengal Cats', 'Mammal','United States', 'The Bengal cat is a domesticated cat breed created from hybrids of domestic cats, especially the spotted Egyptian Mau, with the Asian leopard cat (Prionailurus bengalensis).', '5200', 'true', 'https://media.istockphoto.com/photos/portrait-of-a-bengal-cat-that-rests-on-a-pillow-picture-id868546058?k=6&m=868546058&s=612x612&w=0&h=BAu22aA-dwUhaejYrWsqVqL3FY1uFfJzLPQbg--mXzg='),
('Peppermint Angelfish', 'Actinopterygii (Pomacanthidae)', 'Eastern central Pacific Ocean', 'The peppermint angelfish has a deep, oval shaped body which has five white vertical bars on a reddish-orange background, these bars extending onto the fins, has alternating vertical reddish orange and white bars on the body, head and fins.', '30000', 'false', 'https://www.petage.com/wp-content/uploads/2019/05/PeppermintAngelfish_5-15-19_02-670x447.jpg'),
('Xingu River Ray', 'Chondrichthyes', 'Xingu River basin', 'The Xingu river ray is a venomous stingray that contains venom localized at its dentine spine in its tail.', '100000','true', 'https://media.istockphoto.com/photos/xingu-river-ray-at-sand-background-black-leopoldi-ray-with-yellow-picture-id1165950316?k=6&m=1165950316&s=612x612&w=0&h=AH44ECO2O8_ExwHNCBaTuaxxcReW4NM98iF2-0yCCeE='),
('Leafy Sea Dragon', 'Syngnathidae,', 'Southern & Western Australia', 'Much like the seahorse, the leafy seadragons name is derived from its resemblance to another creature (in this case, the mythical dragon)', '15000', 'true', 'https://media.istockphoto.com/photos/leafy-seahorse-picture-id641474136?k=6&m=641474136&s=612x612&w=0&h=o5s_e2IHJrffBhvJVcFAdRMQEZ_1uoU7VtH04kIGhEo='),
('Australian Flathead Perch', 'Actinopterygii (Epinephelinae)', 'Australia', 'The rainfordia has an overall dark orange colour broken by six black-margined lilac stripes along each flank, the background orange colour is darkest on the centre of the flanks, fading to yellow on the back and belly.', '5000','true', 'https://cdn.shopify.com/s/files/1/0421/4495/6567/products/flatheadperch2square_540x.jpg?v=1622474530'),
('Kinkajou', 'Mammal', 'Central America & South America', 'They are playful, generally quiet, docile, and have little odor. However, they can occasionally be aggressive. Kinkajous dislike sudden movements, noise, and being awake during the day.', '4000', 'true', 'https://media.istockphoto.com/photos/kinkajou-potos-flavus-tropical-animal-isolated-on-white-bakground-picture-id1163968653?k=6&m=1163968653&s=612x612&w=0&h=a8dqttmHCsQ3t24YflLMidUAOe9azGEUfXqucrQXiFo='),
('Frilled Dragon', 'Reptile', 'Northern Australia and southern New Guinea', 'The frill-necked lizard is a relatively large member of the agamid family, growing up to 85 cm (2.79 ft). It is capable of bipedal locomotion and has been described as regularly moving in this manner with a purposeful stride at times by naturalists', '500', 'true', 'https://media.istockphoto.com/photos/frillnecked-lizard-picture-id930950164?k=6&m=930950164&s=612x612&w=0&h=aKf7Cam0cIHjzilZwjDXBbOEqT38_nS5RLM4KOKIKVg=');
